# Generated by Django 4.2.16 on 2025-08-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(db_column='SiteName', max_length=50)),
                ('reported_time_utc', models.DateTimeField(db_column='ReportedTime-UTC')),
                ('voc', models.DecimalField(blank=True, db_column='VOC', decimal_places=4, max_digits=8, null=True)),
                ('o3', models.DecimalField(blank=True, db_column='O3', decimal_places=4, max_digits=8, null=True)),
                ('so2', models.DecimalField(blank=True, db_column='SO2', decimal_places=4, max_digits=8, null=True)),
                ('no2', models.DecimalField(blank=True, db_column='NO2', decimal_places=4, max_digits=8, null=True)),
                ('received_time', models.DateTimeField(blank=True, db_column='ReceivedTime', null=True)),
            ],
            options={
                'db_table': '"AirQualityData-VOC-V6_1"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BatteryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(db_column='SiteName', max_length=50)),
                ('reported_time_utc', models.DateTimeField(db_column='ReportedTime-UTC')),
                ('corrected_battery_voltage', models.DecimalField(blank=True, db_column='corrected_battery_voltage', decimal_places=2, max_digits=5, null=True)),
                ('received_time', models.DateTimeField(blank=True, db_column='ReceivedTime', null=True)),
            ],
            options={
                'db_table': '"AirQualityData-battery-V6_1"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='THData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(db_column='SiteName', max_length=50)),
                ('time', models.DateTimeField(db_column='Time')),
                ('humidity', models.DecimalField(blank=True, db_column='humidity', decimal_places=2, max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, db_column='temperature', decimal_places=2, max_digits=5, null=True)),
                ('noise', models.DecimalField(blank=True, db_column='noise', decimal_places=2, max_digits=5, null=True)),
                ('pm2_5', models.DecimalField(blank=True, db_column='PM2_5', decimal_places=2, max_digits=5, null=True)),
                ('pm10', models.DecimalField(blank=True, db_column='PM10', decimal_places=2, max_digits=5, null=True)),
                ('illumination', models.DecimalField(blank=True, db_column='Illumination', decimal_places=2, max_digits=10, null=True)),
                ('mqtt_sent', models.IntegerField(db_column='mqttSent', default=0)),
            ],
            options={
                'db_table': '"AirQualityData-TH-V6_1"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, db_column='location', max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, db_column='latitude', decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='longitude', decimal_places=6, max_digits=9, null=True)),
                ('elevation', models.IntegerField(blank=True, db_column='elevation', null=True)),
                ('temperature', models.DecimalField(blank=True, db_column='temperature', decimal_places=1, max_digits=5, null=True)),
                ('windspeed', models.DecimalField(blank=True, db_column='windspeed', decimal_places=1, max_digits=5, null=True)),
                ('winddirection', models.SmallIntegerField(blank=True, db_column='winddirection', null=True)),
                ('is_day', models.CharField(blank=True, db_column='is_day', max_length=10, null=True)),
                ('weathercode', models.SmallIntegerField(blank=True, db_column='weathercode', null=True)),
                ('humidity', models.SmallIntegerField(blank=True, db_column='humidity', null=True)),
                ('solar_radiation', models.DecimalField(blank=True, db_column='solar_radiation', decimal_places=2, max_digits=10, null=True)),
                ('pressure', models.DecimalField(blank=True, db_column='pressure', decimal_places=2, max_digits=7, null=True)),
                ('data_time_local', models.DateTimeField(blank=True, db_column='data_time_local', null=True)),
                ('data_time_utc', models.DateTimeField(blank=True, db_column='data_time_utc', null=True)),
                ('fetch_time', models.DateTimeField(blank=True, db_column='fetch_time', null=True)),
            ],
            options={
                'db_table': '"AirQualityData-CorpusChristiWeather-V6_1"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.devicegroup')),
            ],
            options={
                'unique_together': {('group', 'device_name')},
            },
        ),
    ]
