# Generated by Django 4.2.16 on 2025-08-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='THData',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
