# Generated by Django 4.2.16 on 2025-08-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_thdata_remove_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='THData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(db_column='SiteName', max_length=50)),
                ('time', models.DateTimeField(db_column='Time')),
                ('humidity', models.DecimalField(blank=True, db_column='humidity', decimal_places=2, max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, db_column='temperature', decimal_places=2, max_digits=5, null=True)),
                ('noise', models.DecimalField(blank=True, db_column='noise', decimal_places=2, max_digits=5, null=True)),
                ('pm2_5', models.DecimalField(blank=True, db_column='PM2_5', decimal_places=2, max_digits=5, null=True)),
                ('pm10', models.DecimalField(blank=True, db_column='PM10', decimal_places=2, max_digits=5, null=True)),
                ('illumination', models.DecimalField(blank=True, db_column='Illumination', decimal_places=2, max_digits=10, null=True)),
                ('mqtt_sent', models.IntegerField(db_column='mqttSent', default=0)),
            ],
            options={
                'db_table': '"AirQualityData-TH-V6_1"',
                'managed': False,
            },
        ),
    ]
