# Generated by Django 4.2.16 on 2025-09-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_exportedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirQualityData',
        ),
        migrations.DeleteModel(
            name='BatteryData',
        ),
        migrations.DeleteModel(
            name='THData',
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
